server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://nolmung.kr:8761/eureka
#      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/cert/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: community
          uri: lb://COMMUNITY
          predicates:
            - Path=/api/community/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: withdog
          uri: lb://WITHDOG
          predicates:
            - Path=/api/withdog/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: spot
          uri: lb://SPOT
          predicates:
            - Path=/api/spot/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: image
          uri: lb://IMAGE
          predicates:
            - Path=/api/image/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: chat
          uri: http://nolmung.kr:5000
          predicates:
            - Path=/**
          filters:
            - RemoveRequestHeader=Cookie

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

token:
  secret: user_token
