server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://k7a703.p.ssafy.io:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://k7a703.p.ssafy.io:8080/
          predicates:
            - Path=/api/user/**
        - id: community
          uri: http://k7a703.p.ssafy.io:8081/
          predicates:
            - Path=/api/community/**
        - id: withdog
          uri: http://k7a703.p.ssafy.io:8082/
          predicates:
            - Path=/api/withdog/**
        - id: spot
          uri: http://k7a703.p.ssafy.io:8083/
          predicates:
            - Path=/api/spot/**
