spring:
  application:
    name: image

server:
  port: 0
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

resources:
  location: /images/
  uri_path: /images

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://nolmung.kr:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}