spring:
  profiles:
    include: db
  application:
    name: community

server:
  port: 8081
#  address: k7a703.p.ssafy.io
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true


resources:
  location: /images/
  uri_path: /images

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k7a703.p.ssafy.io:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}