server:
  port: 0
  servlet:
    contextPath: /api/withdog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: db
  application:
    name: withdog
  data:
    mongodb:
      uri: mongodb://nolmung.kr:27017/withdog

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://nolmung.kr:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}